name: project_dictionary
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  lottie: ^3.1.3
  flutter_svg: ^2.0.16
  english_words: ^4.0.0
  http: ^1.2.2
  skeletonizer: ^1.4.2
  card_loading: ^0.3.2
  just_audio: ^0.9.42
  shared_preferences: ^2.5.1
  intl: ^0.19.0
  flutter_localization: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/svg/
  fonts:
    - family: JetBrains
      fonts:
        - asset: lib/fonts/KantumruyPro-Regular.ttf
  generate: true
